version: '3'
services:
  unstable-nginx:
    depends_on:
      - unstable-server
      - unstable-client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "8000:80"
    networks:
      - unicorn_network

  unstable-server:
    build: ./server
    image: unstable_unicorn:latest
    tty: true
    depends_on:
      - mongodb
    volumes: 
      - ./server:/usr/src/app/server
    ports:
      - 9229:9229
    networks:
      - unicorn_network

  unstable-client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - ./client:/app
    networks:
      - unicorn_network

  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - ./data-node:/data/db
    ports:
      - 27017:27017
    command: mongod --noauth
    networks:
      - unicorn_network
networks:
  unicorn_network:
    driver: bridge