export enum Events {
    ENTERED_STABLE = 'entered',
    DESTROYED = 'destroyed',
    CARD_PLAYED = 'cardPlayed',
    DISCARDED = 'cardDiscard',
    RESOLVE_CHAIN = 'resolve',
    ADD_GAME_ACTION = "addAction",
    ON_PLAYER_ACTION = "ON_PLAYER_ACTION",
    REMOVE_EXPECTED_ACTION = "REMOVE_EXPECTED_ACTION",
    PUSH_TO_CHAIN = "PUSH_TO_CHAIN",
    DISCARD_FROM_CHAIN_IF_EXISTS = "DISCARD_FROM_CHAIN_IF_EXISTS",
    BEFORE_RESOLVE_CHAIN = "BEFORE_RESOLVE_CHAIN",
    BEFORE_TURN_START = "BEFORE_TURN_START",
    TURN_START = "TURN_START",
    AFTER_DESTROY = "AFTER_DESTROY",
    FORCE_END_TURN = "FORCE_END_TURN"
}